name: Deploy del proyecto .NET API a Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Reemplazo de Credenciales de JWT en appSettings.json
        shell: bash
        run: |
          sed -i 's|\$JWT_AUDIENCE|'"${{ secrets.JWT_AUDIENCE }}"'|g' CalculadoraCedears.Api/appsettings.Development.json
          sed -i 's|\$JWT_ISSUER|'"${{ secrets.JWT_ISSUER }}"'|g' CalculadoraCedears.Api/appsettings.Development.json
          sed -i 's|\$JWT_SECRET|'"${{ secrets.JWT_SECRET }}"'|g' CalculadoraCedears.Api/appsettings.Development.json
          sed -i 's|\$GOOGLE_CLIENT_ID|'"${{ secrets.GOOGLE_CLIENT_ID }}"'|g' CalculadoraCedears.Api/appsettings.Development.json
          sed -i 's|\$GOOGLE_SECRET|'"${{ secrets.GOOGLE_CLIENT_SECRET }}"'|g' CalculadoraCedears.Api/appsettings.Development.json
          sed -i 's|\$GOOGLE_REDIRECT_URI|'"${{ secrets.GOOGLE_REDIRECT_URI }}"'|g' CalculadoraCedears.Api/appsettings.Development.json
          sed -i 's|\$SQL_CONNECTION_STRING|'"${{ secrets.SQL_CONNECTION_STRING }}"'|g' CalculadoraCedears.Api/appsettings.Development.json

      - name: Restore dependencias
        run: dotnet restore CalculadoraCedears.Api/CalculadoraCedears.Api.csproj

      - name: Unit test
        run: dotnet test CalculadoraCedears.Api.Unit.Tests/CalculadoraCedears.Api.Unit.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Build
        run: dotnet build --configuration Release CalculadoraCedears.Api/CalculadoraCedears.Api.csproj

      - name: MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build DACPAC
        run: |
          msbuild CalculadoraCedears.Api.Db/CalculadoraCedears.Api.Db.sqlproj /p:Configuration=Release /p:Dsp=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider /p:OutputPath=./dacpac
        shell: powershell

      - name: Verificar archivo DACPAC
        run: |
            dir CalculadoraCedears.Api.Db/dacpac/
        shell: powershell

      - name: Publicar DACPAC a Azure SQL
        uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: "CalculadoraCedears.Api.Db/dacpac/CalculadoraCedears.Api.Db.dacpac"
          action: Publish

      - name: Publicar Api .NET
        run: dotnet publish -c Release -o ./publish CalculadoraCedears.Api/CalculadoraCedears.Api.csproj

      - name: Deploy de la API a Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish          
