name: 'publish'

on:
  push:
    branches:
      - main

# Este workflow se ejecuta en cada push a la rama `main` para crear una release de GitHub,
# construir tu aplicación Tauri y subir los artefactos generados.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install
        working-directory: CalculadoraCedears.Desktop

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: CalculadoraCedears.Desktop
          tagName: Release-v__VERSION__ # __VERSION__ se reemplaza por la versión de tu tauri.conf.json
          releaseName: 'CalculadoraCedears v__VERSION__'
          releaseBody: 'Vea los recursos para descargar e instalarla la aplicación.'
          includeUpdaterJson: true 
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
